import { Card } from '@/models/Card';

const Deck: { [key: string]: Card } = {
  1: { id: 1, suite: 'bez', type: 'JOKER' },
  2: { id: 2, suite: 'bez', type: 'JOKER' },
  3: { id: 3, suite: 'spade', type: '7' },
  4: { id: 4, suite: 'spade', type: '8' },
  5: { id: 5, suite: 'spade', type: '9' },
  6: { id: 6, suite: 'spade', type: '10' },
  7: { id: 7, suite: 'spade', type: 'J' },
  8: { id: 8, suite: 'spade', type: 'Q' },
  9: { id: 9, suite: 'spade', type: 'K' },
  10: { id: 10, suite: 'spade', type: 'A' },
  11: { id: 11, suite: 'club', type: '7' },
  12: { id: 12, suite: 'club', type: '8' },
  13: { id: 13, suite: 'club', type: '9' },
  14: { id: 14, suite: 'club', type: '10' },
  15: { id: 15, suite: 'club', type: 'J' },
  16: { id: 16, suite: 'club', type: 'Q' },
  17: { id: 17, suite: 'club', type: 'K' },
  18: { id: 18, suite: 'club', type: 'A' },
  19: { id: 19, suite: 'diamond', type: '6' },
  20: { id: 20, suite: 'diamond', type: '7' },
  21: { id: 21, suite: 'diamond', type: '8' },
  22: { id: 22, suite: 'diamond', type: '9' },
  23: { id: 23, suite: 'diamond', type: '10' },
  24: { id: 24, suite: 'diamond', type: 'J' },
  25: { id: 25, suite: 'diamond', type: 'Q' },
  26: { id: 26, suite: 'diamond', type: 'K' },
  27: { id: 27, suite: 'diamond', type: 'A' },
  28: { id: 28, suite: 'hart', type: '6' },
  29: { id: 29, suite: 'hart', type: '7' },
  30: { id: 30, suite: 'hart', type: '8' },
  31: { id: 31, suite: 'hart', type: '9' },
  32: { id: 32, suite: 'hart', type: '10' },
  33: { id: 33, suite: 'hart', type: 'J' },
  34: { id: 34, suite: 'hart', type: 'Q' },
  35: { id: 35, suite: 'hart', type: 'K' },
  36: { id: 36, suite: 'hart', type: 'A' },
};
export default Deck;
